language: python
python:
  - "2.6"
  - "2.7"
  
# command to install dependencies
install:
  - "pip install -r shinken/dependencies"
  - "./bin/preparedev"
# command to run tests
script:
  - cd test
  - nosetests -xv --process-restartworker --processes=1 --process-timeout=999999999
